### ISSUE TITLE
responseTypeHeader vs response_time_header

### ISSUE THREAD

**Issue by JuanJo4** [oakserver/middleware#2]
Hi,

In documentation and in the code I'm seeing references for `response_time_header` and others to `responseTypeHeader`, is that a typo or is it intentional? which one should be valid? `type` vs `time`?

Happy to help if needed!

**Comment by kitsonk** [comment]
It is unintentional.  It all should be "time".

**Comment by clintwood** [comment]
@kitsonk - So this is not fixed yet but closed!  There is a dangling commit referenced at [ff4218a](athttps://github.com/oakserver/middleware/commit/ff4218a9381168b4541a0910af3e47eadde50778) ??

**Comment by kitsonk** [comment]
Relanded in dd0b75f3bb03882368043aae70ea9394aaa030bf
